import Navbar from "@/components/Navbar";
import "./globals.css";
import { Sora } from "next/font/google";
import Footer from "@/components/Footer";
import Providers from "@/components/Provider";

const inter = Sora({ subsets: ["latin"] });

const Wrapper = ({ children }: { children: React.ReactNode }) => {
  return <div className="max-w-6xl  md:mx-auto">{children}</div>;
};

export const metadata = {
  title: "Ecommerce-Sanity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
          <Navbar />
          <Providers>{children}</Providers>
          <Footer />
        </Wrapper>
      </body>
    </html>
  );
}
